export { default as ErrorMessage } from "./ErrorMessage/ErrorMessage";
export { default as Loader } from "./Loader/Loader";
export { default as Header } from "./Header/Header";
export { default as PeopleList } from "./PeoplePage/PeopleList/PeopleList";
export { default as PeopleNavigate } from "./PeoplePage/PeopleNavigate/PeopleNavigate";
export { default as PersonInfo } from "./PersonPage/PersonInfo/PersonInfo";
export { default as PersonPhoto } from "./PersonPage/PersonPhoto/PersonPhoto";
export { default as PersonGoBack } from "./PersonPage/PersonGoBack/PersonGoBack";
export { default as PersonFilms } from "./PersonPage/PersonFilms/PersonFilms";